main: q2p.quickclick.QuickClick
name: QuickClick
version: 1.0
author: q2p
description: QuickClick Meta Plugin
commands:
  howto:
    description: Guide
    usage: /howto
  build:
    description: Building
    usage: /build <arguments...>
  modifie:
    description: Modifications
    usage: /modifie <arguments...>
  news:
    description: News
    usage: /news <arguments...>
  vacation:
    description: Ban player
    usage: /vacation <name>
  endvacation:
    description: Unban player
    usage: /endvacation <name>
  onvacation:
    description: Checks if player is banned
    usage: /onvacation <name>
  register:
    description: Registers player
    usage: /register <password> <password> <secret word> <secret word>
  login:
    description: Logins player
    usage: /login <password>
  changepassword:
    description: Changes password
    usage: /changepassword <old password> <new password> <new password>
  restorepassword:
    description: Resets password
    usage: /resetpassword <secret word>
  authfix:
    description: Changes password
    usage: /authfix <name> [new password] [new secret word]
  parcour:
    description: Returns player record
    usage: /parcour [name]
  benchmark:
    description: Toggles benchmark
    usage: /benchmark
  duel:
    description: Begins duel between players (remake later)
    usage: /duel <opponent> <level name>
  rail:
    description: forfun (remove later)
    usage: /rail <effect name>
